INSERT INTO CURSOS (nombre) values ('COMUNICACION');
INSERT INTO CURSOS (nombre) values ('CTA');
INSERT INTO CURSOS (nombre) values ('INGLES');
INSERT INTO CURSOS (nombre) values ('FRENCH');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Laura','Hutchinson','cwillis@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Laura','Randolph','alyssa09@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Timothy','Clark','aaronmcclure@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kimberly','Thomas','cartersteven@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Brett','Russell','george21@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Paul','Floyd','jacksonvalerie@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Connie','Anderson','rachelward@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Brendan','Riley','cassandra81@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Paula','Johnson','colesamantha@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Vincent','Ward','bondbeth@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Natalie','Friedman','matthew44@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Christina','Williams','tguerrero@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('William','Martin','oalvarez@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Amy','Smith','chaley@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Sarah','Stewart','karendavis@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Michael','Drake','crosbythomas@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Ricky','Baldwin','qjackson@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kelly','Deleon','charleswilson@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('James','Fox','jwebb@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Paula','Cantu','qcampbell@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Elizabeth','Gregory','leslierice@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Brianna','Lowe','lance35@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Dylan','Wallace','andrewslauren@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Whitney','Reynolds','cherylhull@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Casey','Hawkins','jacksondakota@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Andrew','Peters','sharpkevin@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('David','Delgado','mccartyscott@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Nicole','Butler','jeffrey90@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Adrian','Young','gregory15@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Julia','Hart','kristin45@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Mary','Johnson','lindamoore@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Michael','Mitchell','scottgreene@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Christopher','Ramirez','kevin88@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Joseph','Wood','elizabethwilliams@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Michael','Warren','adam39@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Audrey','Thomas','danieljuarez@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Rodney','Finley','christopherjohnson@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Amanda','Castillo','heathercole@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Cody','Bryan','mcconnellnancy@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Anthony','Garner','grantnicole@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Zachary','Suarez','ymichael@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Monica','Vasquez','qjones@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Jacob','Taylor','tammy68@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Keith','Rodriguez','jennifer51@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('David','Sharp','johngibson@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Douglas','Duncan','afarley@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Jennifer','Douglas','adamstheodore@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Hannah','Campbell','anthonydiaz@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Anita','King','wtrujillo@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Lisa','Graham','hectorbarry@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kayla','Taylor','chris55@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kelly','Allison','hurleystephanie@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kenneth','Reyes','bwatson@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Richard','Wood','jeffrey07@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Raymond','Morris','darlene29@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Sarah','Murillo','efranco@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Eddie','Johnson','marissalewis@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Ronald','Castillo','bnorton@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Taylor','Mathis','ymcdonald@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Michelle','Huber','sarah48@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Angela','Armstrong','garciamatthew@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kimberly','Sanchez','russelljason@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Erin','Rhodes','pwilliams@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Monica','Hunter','moraalexander@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Rachel','Sanchez','williamsrobert@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Shawn','Miller','fjones@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Joseph','Novak','rodriguezkrista@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Jesse','Thompson','david18@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Morgan','Chang','lisa41@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Marcus','Williams','colinmullins@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Clifford','Ayala','donnakelly@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Jennifer','Whitehead','davenportchristine@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Alex','Rubio','taylorhannah@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Mary','Houston','hmejia@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Manuel','Hunt','reyeslinda@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Joan','Gibson','pamgreene@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Sharon','Sloan','paulpena@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Timothy','Gregory','ramosjacob@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Matthew','Nelson','leslieflores@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Jessica','Taylor','grahammicheal@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Christine','Fry','carpenteralfred@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Krista','Huff','clarson@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Rachel','Smith','colebrandon@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Johnathan','Pollard','zstevenson@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Martin','Salas','youngbryan@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kenneth','Nelson','amason@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Brandon','Ponce','laurencole@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Katherine','Davis','bennettconnor@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Kathryn','Silva','stewartjulie@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Joseph','Ferguson','maria55@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Aaron','Stewart','ochristensen@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Amber','Thomas','larryclements@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Laurie','Washington','myersbarbara@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Shaun','Montoya','rogersnathan@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Jennifer','Goodwin','jacob68@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Stacy','Miller','amanda07@hotmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Valerie','Sutton','amanda19@gmail.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Cory','Reid','lauriewhite@yahoo.com');
INSERT INTO ALUMNOS (nombre,apellido,correo) VALUES('Brian','Schmitt','ssimpson@yahoo.com');
INSERT INTO ALUMNOS_CURSOS (ALUMNO_ID, CURSO_ID) VALUES(1,3);
INSERT INTO ALUMNOS_CURSOS (ALUMNO_ID, CURSO_ID) VALUES(10,1);
INSERT INTO ALUMNOS_CURSOS (ALUMNO_ID, CURSO_ID) VALUES(10,2);
INSERT INTO ALUMNOS_CURSOS (ALUMNO_ID, CURSO_ID) VALUES(32,1);
INSERT INTO ALUMNOS_CURSOS (ALUMNO_ID, CURSO_ID) VALUES(55,4);
INSERT INTO ALUMNOS_CURSOS (ALUMNO_ID, CURSO_ID) VALUES(86,3);

